"""Python reference policy renderer for compiler IR/spec."""

from __future__ import annotations

import json

from vellum_core.api.errors import framework_error
from vellum_core.policy_compiler.models import DecisionExpr, PolicyDSLSpec, ValueRef


def render_python_source(spec: PolicyDSLSpec, *, spec_hash: str) -> str:
    """Render deterministic generated Python reference policy."""
    batch_size = spec.batch.batch_size
    reference_policy = spec.reference_policy
    policy_id = spec.policy_id
    decision_agg = "all" if spec.decision.kind == "all" else "any"
    idx_counter = [1]
    decision_inner_expr = render_python_boolean_expr(
        spec.decision.inner,
        idx_var="idx_0",
        idx_counter=idx_counter,
    )
    decision_expr = f'{decision_agg}(({decision_inner_expr}) for idx_0 in range(active_count))'
    decision_uses_policy_params = "policy_params[" in decision_expr

    parameter_order = list(spec.policy_parameters.keys())
    needs_policy_params_hash = bool(parameter_order) or any(
        output.expr == "policy_params_hash" for output in spec.outputs.values()
    )
    project_outputs_uses_policy_params = (
        decision_uses_policy_params
        or any(output.expr == "policy_params_hash" for output in spec.outputs.values())
    )
    parameter_specs = {
        name: {
            "minimum": param.minimum,
            "maximum": param.maximum,
            "default": param.default,
        }
        for name, param in spec.policy_parameters.items()
    }
    output_lines = _render_output_lines(spec)
    policy_input_lines: list[str] = [
        '            "balances": list(normalized_evidence["balances"]),',
        '            "limits": list(normalized_evidence["limits"]),',
        '            "active_count": int(normalized_evidence["active_count"]),',
    ]
    to_private_input_policy_params_line = ""
    if parameter_order:
        to_private_input_policy_params_line = (
            '        policy_params = dict(normalized_evidence.get("policy_parameters", {}))\n'
        )
        policy_input_lines.extend(
            [
                '            "policy_params": [int(policy_params[name]) for name in self.POLICY_PARAMETER_ORDER],',
                '            "expected_policy_params_hash": compute_policy_params_hash(policy_params),',
            ]
        )
    evaluate_policy_params_line = ""
    if decision_uses_policy_params:
        evaluate_policy_params_line = (
            '        policy_params = dict(normalized_evidence.get("policy_parameters", {}))\n'
        )
    project_policy_params_line = ""
    if project_outputs_uses_policy_params:
        project_policy_params_line = (
            '        policy_params = dict(normalized_evidence.get("policy_parameters", {}))\n'
        )

    return f'''"""Generated by vellum-compiler {spec.compiler_version}; do not edit manually."""

from __future__ import annotations

from typing import Any

from vellum_core.api.errors import framework_error
from vellum_core.logic.batcher import MAX_UINT32, batch_prepare_from_private_input, batch_prepare_input
{"from vellum_core.policy_parameters import compute_policy_params_hash" if needs_policy_params_hash else ""}
from vellum_core.policies.base import PolicyDecision
from vellum_core.policies.normalization import require_integer_list


class GeneratedReferencePolicy:
    """Generated reference policy for `{policy_id}`."""

    reference_policy = "{reference_policy}"
    policy_id = "{policy_id}"
    spec_hash = "{spec_hash}"
    batch_size = {batch_size}
    POLICY_PARAMETER_ORDER = {json.dumps(parameter_order)}
    POLICY_PARAMETER_SPECS = {json.dumps(parameter_specs, sort_keys=True)}

    def validate(self, evidence_payload: dict[str, Any]) -> None:
        _ = self.normalize(evidence_payload)

    def normalize(self, evidence_payload: dict[str, Any]) -> dict[str, Any]:
        policy_params = self._resolve_policy_parameters(evidence_payload.get("policy_parameters"))

        private_input = evidence_payload.get("private_input")
        if isinstance(private_input, dict):
            try:
                prepared = batch_prepare_from_private_input(private_input)
            except ValueError as exc:
                raise framework_error(
                    "invalid_evidence_payload",
                    "Evidence payload failed batch validation",
                    reason=str(exc),
                ) from exc
            normalized = prepared.to_circuit_input()
            normalized["policy_parameters"] = policy_params
            return normalized

        balances = require_integer_list(
            field="balances",
            value=evidence_payload.get("balances"),
            minimum=0,
            maximum=MAX_UINT32,
        )
        limits = require_integer_list(
            field="limits",
            value=evidence_payload.get("limits"),
            minimum=0,
            maximum=MAX_UINT32,
        )
        try:
            prepared = batch_prepare_input(balances=balances, limits=limits, batch_size=self.batch_size)
        except ValueError as exc:
            raise framework_error(
                "invalid_evidence_payload",
                "Evidence payload failed batch validation",
                reason=str(exc),
            ) from exc
        normalized = prepared.to_circuit_input()
        normalized["policy_parameters"] = policy_params
        return normalized

    def to_private_input(self, normalized_evidence: dict[str, Any]) -> dict[str, Any]:
{to_private_input_policy_params_line.rstrip()}
        return {{
{chr(10).join(policy_input_lines)}
        }}

    def evaluate_reference(self, normalized_evidence: dict[str, Any]) -> PolicyDecision:
        active_count = int(normalized_evidence["active_count"])
        balances = list(normalized_evidence["balances"])
        limits = list(normalized_evidence["limits"])
{evaluate_policy_params_line.rstrip()}
        decision = {decision_expr}
        return "pass" if decision else "fail"

    def project_public_outputs(self, normalized_evidence: dict[str, Any]) -> dict[str, Any]:
        active_count = int(normalized_evidence["active_count"])
        balances = list(normalized_evidence["balances"])
        limits = list(normalized_evidence["limits"])
{project_policy_params_line.rstrip()}
        all_valid = {decision_expr}
        return {{
{output_lines}
        }}

    def _resolve_policy_parameters(self, payload: Any) -> dict[str, int]:
        if not self.POLICY_PARAMETER_ORDER:
            return {{}}
        if payload is None:
            payload = {{}}
        if not isinstance(payload, dict):
            raise framework_error(
                "invalid_evidence_payload",
                "policy_parameters must be an object",
            )
        resolved: dict[str, int] = {{}}
        unknown = sorted(set(str(key) for key in payload.keys()) - set(self.POLICY_PARAMETER_ORDER))
        if unknown:
            raise framework_error(
                "invalid_evidence_payload",
                "policy_parameters contains unknown keys",
                unknown=unknown,
            )
        for name in self.POLICY_PARAMETER_ORDER:
            spec = self.POLICY_PARAMETER_SPECS[name]
            value = payload.get(name, spec.get("default"))
            if value is None:
                raise framework_error(
                    "invalid_evidence_payload",
                    "policy_parameters missing required key",
                    key=name,
                )
            if isinstance(value, bool) or not isinstance(value, int):
                raise framework_error(
                    "invalid_evidence_payload",
                    "policy_parameters values must be integers",
                    key=name,
                    value=value,
                )
            minimum = spec.get("minimum")
            maximum = spec.get("maximum")
            if minimum is not None and value < int(minimum):
                raise framework_error(
                    "invalid_evidence_payload",
                    "policy_parameters value below minimum",
                    key=name,
                    minimum=int(minimum),
                    value=value,
                )
            if maximum is not None and value > int(maximum):
                raise framework_error(
                    "invalid_evidence_payload",
                    "policy_parameters value above maximum",
                    key=name,
                    maximum=int(maximum),
                    value=value,
                )
            resolved[name] = int(value)
        return resolved
'''


def render_python_boolean_expr(
    expr: DecisionExpr,
    *,
    idx_var: str,
    idx_counter: list[int],
) -> str:
    """Render one boolean expression as Python code."""
    if expr.kind == "comparison":
        assert expr.comparison is not None
        left = render_python_value(expr.comparison.left, idx_var=idx_var)
        right = render_python_value(expr.comparison.right, idx_var=idx_var)
        return f"({left} {python_operator_token(expr.comparison.op)} {right})"
    if expr.kind == "and":
        return (
            "("
            + " and ".join(
                render_python_boolean_expr(arg, idx_var=idx_var, idx_counter=idx_counter)
                for arg in expr.args
            )
            + ")"
        )
    if expr.kind == "or":
        return (
            "("
            + " or ".join(
                render_python_boolean_expr(arg, idx_var=idx_var, idx_counter=idx_counter)
                for arg in expr.args
            )
            + ")"
        )
    if expr.kind == "not":
        assert expr.inner is not None
        inner = render_python_boolean_expr(expr.inner, idx_var=idx_var, idx_counter=idx_counter)
        return f"(not ({inner}))"
    if expr.kind in {"all", "any"}:
        assert expr.inner is not None
        nested_var = f"idx_{idx_counter[0]}"
        idx_counter[0] += 1
        agg_token = "all" if expr.kind == "all" else "any"
        inner = render_python_boolean_expr(expr.inner, idx_var=nested_var, idx_counter=idx_counter)
        return f"{agg_token}(({inner}) for {nested_var} in range(active_count))"

    raise framework_error(
        "policy_spec_unsupported",
        "Unsupported decision expression in Python renderer",
        kind=expr.kind,
    )


def render_python_value(value: ValueRef, *, idx_var: str) -> str:
    """Render one value node as Python expression."""
    if value.const_int is not None:
        return str(value.const_int)
    if value.param is not None:
        return f'policy_params["{value.param}"]'
    ref = value.ref
    if ref == "balances":
        return f"balances[{idx_var}]"
    if ref == "limits":
        return f"limits[{idx_var}]"
    if ref == "active_count":
        return "active_count"
    if isinstance(ref, str) and ref.startswith("policy_params."):
        return f'policy_params["{ref.split(".", 1)[1]}"]'
    raise framework_error(
        "policy_spec_unsupported",
        "Unsupported value reference in Python renderer",
        ref=ref,
    )


def python_operator_token(op: str) -> str:
    """Map comparison operators to valid Python tokens."""
    if op in {"<", ">", "<=", ">=", "=="}:
        return op
    raise framework_error(
        "policy_spec_unsupported",
        "Compiler received unsupported comparison operator",
        operator=op,
    )


def _render_output_lines(spec: PolicyDSLSpec) -> str:
    lines: list[str] = []
    for output_name, output in spec.outputs.items():
        if output.expr == "decision":
            lines.append(f'            "{output_name}": all_valid,')
            continue
        if output.expr == "active_count":
            lines.append(f'            "{output_name}": active_count,')
            continue
        if output.expr == "policy_params_hash":
            lines.append(f'            "{output_name}": compute_policy_params_hash(policy_params),')
            continue
        raise framework_error(
            "policy_spec_unsupported",
            "Unsupported output expression in Python renderer",
            output=output_name,
            expr=output.expr,
        )
    return "\n".join(lines)
