"""Python reference policy renderer for compiler IR/spec."""

from __future__ import annotations

from vellum_core.api.errors import framework_error
from vellum_core.policy_compiler.models import DecisionExpr, PolicyDSLSpec, ValueRef


def render_python_source(spec: PolicyDSLSpec, *, spec_hash: str) -> str:
    """Render deterministic generated Python reference policy."""
    batch_size = spec.batch.batch_size
    reference_policy = spec.reference_policy
    policy_id = spec.policy_id
    decision_agg = "all" if spec.decision.kind == "all" else "any"
    idx_counter = [1]
    decision_inner_expr = render_python_boolean_expr(
        spec.decision.inner,
        idx_var="idx_0",
        idx_counter=idx_counter,
    )
    decision_expr = f'{decision_agg}(({decision_inner_expr}) for idx_0 in range(active_count))'
    return f'''"""Generated by vellum-compiler {spec.compiler_version}; do not edit manually."""

from __future__ import annotations

from typing import Any

from vellum_core.api.errors import framework_error
from vellum_core.logic.batcher import MAX_UINT32, batch_prepare_from_private_input, batch_prepare_input
from vellum_core.policies.base import PolicyDecision
from vellum_core.policies.normalization import require_integer_list


class GeneratedReferencePolicy:
    """Generated reference policy for `{policy_id}`."""

    reference_policy = "{reference_policy}"
    policy_id = "{policy_id}"
    spec_hash = "{spec_hash}"
    batch_size = {batch_size}

    def validate(self, evidence_payload: dict[str, Any]) -> None:
        _ = self.normalize(evidence_payload)

    def normalize(self, evidence_payload: dict[str, Any]) -> dict[str, Any]:
        private_input = evidence_payload.get("private_input")
        if isinstance(private_input, dict):
            try:
                prepared = batch_prepare_from_private_input(private_input)
            except ValueError as exc:
                raise framework_error(
                    "invalid_evidence_payload",
                    "Evidence payload failed batch validation",
                    reason=str(exc),
                ) from exc
            return prepared.to_circuit_input()

        balances = require_integer_list(
            field="balances",
            value=evidence_payload.get("balances"),
            minimum=0,
            maximum=MAX_UINT32,
        )
        limits = require_integer_list(
            field="limits",
            value=evidence_payload.get("limits"),
            minimum=0,
            maximum=MAX_UINT32,
        )
        try:
            prepared = batch_prepare_input(balances=balances, limits=limits, batch_size=self.batch_size)
        except ValueError as exc:
            raise framework_error(
                "invalid_evidence_payload",
                "Evidence payload failed batch validation",
                reason=str(exc),
            ) from exc
        return prepared.to_circuit_input()

    def to_private_input(self, normalized_evidence: dict[str, Any]) -> dict[str, Any]:
        return {{
            "balances": list(normalized_evidence["balances"]),
            "limits": list(normalized_evidence["limits"]),
            "active_count": int(normalized_evidence["active_count"]),
        }}

    def evaluate_reference(self, normalized_evidence: dict[str, Any]) -> PolicyDecision:
        active_count = int(normalized_evidence["active_count"])
        balances = list(normalized_evidence["balances"])
        limits = list(normalized_evidence["limits"])
        decision = {decision_expr}
        return "pass" if decision else "fail"

    def project_public_outputs(self, normalized_evidence: dict[str, Any]) -> dict[str, Any]:
        active_count = int(normalized_evidence["active_count"])
        balances = list(normalized_evidence["balances"])
        limits = list(normalized_evidence["limits"])
        all_valid = {decision_expr}
        return {{
            "all_valid": all_valid,
            "active_count_out": active_count,
        }}
'''


def render_python_boolean_expr(
    expr: DecisionExpr,
    *,
    idx_var: str,
    idx_counter: list[int],
) -> str:
    """Render one boolean expression as Python code."""
    if expr.kind == "comparison":
        assert expr.comparison is not None
        left = render_python_value(expr.comparison.left, idx_var=idx_var)
        right = render_python_value(expr.comparison.right, idx_var=idx_var)
        return f"({left} {python_operator_token(expr.comparison.op)} {right})"
    if expr.kind == "and":
        return (
            "("
            + " and ".join(
                render_python_boolean_expr(arg, idx_var=idx_var, idx_counter=idx_counter)
                for arg in expr.args
            )
            + ")"
        )
    if expr.kind == "or":
        return (
            "("
            + " or ".join(
                render_python_boolean_expr(arg, idx_var=idx_var, idx_counter=idx_counter)
                for arg in expr.args
            )
            + ")"
        )
    if expr.kind == "not":
        assert expr.inner is not None
        inner = render_python_boolean_expr(expr.inner, idx_var=idx_var, idx_counter=idx_counter)
        return f"(not ({inner}))"
    if expr.kind in {"all", "any"}:
        assert expr.inner is not None
        nested_var = f"idx_{idx_counter[0]}"
        idx_counter[0] += 1
        agg_token = "all" if expr.kind == "all" else "any"
        inner = render_python_boolean_expr(expr.inner, idx_var=nested_var, idx_counter=idx_counter)
        return f"{agg_token}(({inner}) for {nested_var} in range(active_count))"

    raise framework_error(
        "policy_spec_unsupported",
        "Unsupported decision expression in Python renderer",
        kind=expr.kind,
    )


def render_python_value(value: ValueRef, *, idx_var: str) -> str:
    """Render one value node as Python expression."""
    if value.const_int is not None:
        return str(value.const_int)
    ref = value.ref
    if ref == "balances":
        return f"balances[{idx_var}]"
    if ref == "limits":
        return f"limits[{idx_var}]"
    if ref == "active_count":
        return "active_count"
    raise framework_error(
        "policy_spec_unsupported",
        "Unsupported value reference in Python renderer",
        ref=ref,
    )


def python_operator_token(op: str) -> str:
    """Map comparison operators to valid Python tokens."""
    if op in {"<", ">", "<=", ">=", "=="}:
        return op
    raise framework_error(
        "policy_spec_unsupported",
        "Compiler received unsupported comparison operator",
        operator=op,
    )
