{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "vellum-core.fullname" . }}
  labels:
{{ toYaml .Values.serviceMonitor.labels | indent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "vellum-core.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
  - port: http
    interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
