apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vellum-core.fullname" . }}-worker
spec:
  replicas: {{ .Values.replicaCount.worker }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "vellum-core.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "vellum-core.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: worker
    spec:
      serviceAccountName: {{ include "vellum-core.serviceAccountName" . }}
      securityContext:
{{ toYaml .Values.podSecurityContext | indent 8 }}
      containers:
      - name: worker
        image: "{{ .Values.images.worker.repository }}:{{ .Values.images.worker.tag }}"
        imagePullPolicy: {{ .Values.images.worker.pullPolicy }}
        command: ["celery", "-A", "vellum_core.celery_app", "worker", "-Q", "{{ .Values.keda.queueName }}", "-l", "info"]
        env:
{{ include "vellum-core.commonEnv" . | indent 10 }}
        - name: APP_NAME
          value: {{ printf "%s-worker" .Values.env.appNamePrefix | quote }}
        securityContext:
{{ toYaml .Values.securityContext | indent 10 }}
        resources:
{{ toYaml .Values.resources.worker | indent 10 }}
