# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vellum_prover.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13vellum_prover.proto\x12\x13vellum.nativeprover\"l\n\x14GenerateProofRequest\x12\x12\n\ncircuit_id\x18\x01 \x01(\t\x12\x1a\n\x12private_input_json\x18\x02 \x01(\t\x12\x11\n\twasm_path\x18\x03 \x01(\t\x12\x11\n\tzkey_path\x18\x04 \x01(\t\"H\n\x15GenerateProofResponse\x12\x12\n\nproof_json\x18\x01 \x01(\t\x12\x1b\n\x13public_signals_json\x18\x02 \x01(\t\"x\n\x12VerifyProofRequest\x12\x12\n\ncircuit_id\x18\x01 \x01(\t\x12\x12\n\nproof_json\x18\x02 \x01(\t\x12\x1b\n\x13public_signals_json\x18\x03 \x01(\t\x12\x1d\n\x15verification_key_path\x18\x04 \x01(\t\"$\n\x13VerifyProofResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x32\xd2\x01\n\x06Prover\x12\x66\n\rGenerateProof\x12).vellum.nativeprover.GenerateProofRequest\x1a*.vellum.nativeprover.GenerateProofResponse\x12`\n\x0bVerifyProof\x12\'.vellum.nativeprover.VerifyProofRequest\x1a(.vellum.nativeprover.VerifyProofResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vellum_prover_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GENERATEPROOFREQUEST._serialized_start=44
  _GENERATEPROOFREQUEST._serialized_end=152
  _GENERATEPROOFRESPONSE._serialized_start=154
  _GENERATEPROOFRESPONSE._serialized_end=226
  _VERIFYPROOFREQUEST._serialized_start=228
  _VERIFYPROOFREQUEST._serialized_end=348
  _VERIFYPROOFRESPONSE._serialized_start=350
  _VERIFYPROOFRESPONSE._serialized_end=386
  _PROVER._serialized_start=389
  _PROVER._serialized_end=599
# @@protoc_insertion_point(module_scope)
