# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from vellum_core.proto import vellum_prover_pb2 as vellum__prover__pb2


class ProverStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateProof = channel.unary_unary(
                '/vellum.nativeprover.Prover/GenerateProof',
                request_serializer=vellum__prover__pb2.GenerateProofRequest.SerializeToString,
                response_deserializer=vellum__prover__pb2.GenerateProofResponse.FromString,
                )
        self.VerifyProof = channel.unary_unary(
                '/vellum.nativeprover.Prover/VerifyProof',
                request_serializer=vellum__prover__pb2.VerifyProofRequest.SerializeToString,
                response_deserializer=vellum__prover__pb2.VerifyProofResponse.FromString,
                )


class ProverServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateProof(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyProof(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProverServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateProof': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateProof,
                    request_deserializer=vellum__prover__pb2.GenerateProofRequest.FromString,
                    response_serializer=vellum__prover__pb2.GenerateProofResponse.SerializeToString,
            ),
            'VerifyProof': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyProof,
                    request_deserializer=vellum__prover__pb2.VerifyProofRequest.FromString,
                    response_serializer=vellum__prover__pb2.VerifyProofResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vellum.nativeprover.Prover', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Prover(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateProof(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vellum.nativeprover.Prover/GenerateProof',
            vellum__prover__pb2.GenerateProofRequest.SerializeToString,
            vellum__prover__pb2.GenerateProofResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def VerifyProof(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vellum.nativeprover.Prover/VerifyProof',
            vellum__prover__pb2.VerifyProofRequest.SerializeToString,
            vellum__prover__pb2.VerifyProofResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
